"""empty message

Revision ID: 13ea2fed1435
Revises: 
Create Date: 2020-01-14 23:08:53.081220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ea2fed1435'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=True),
    sa.Column('input_text', sa.String(length=50), nullable=True),
    sa.Column('target_language_id', sa.Integer(), nullable=True),
    sa.Column('output_text', sa.String(length=50), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['translations_status.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )

    op.execute("INSERT INTO languages (id, language) VALUES (1, 'en')")
    op.execute("INSERT INTO languages (id, language) VALUES (2, 'es')")
    op.execute("INSERT INTO translations_status (id, status) VALUES (1, 'requested')")
    op.execute("INSERT INTO translations_status (id, status) VALUES (2, 'pending')")
    op.execute("INSERT INTO translations_status (id, status) VALUES (3, 'translated')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('translations_status')
    op.drop_table('languages')
    # ### end Alembic commands ###
